using Content.Client.UserInterface.Controls;
using Content.Shared.InvestigationExaminable;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Wormix.InvestigationExaminable;


[GenerateTypedNameReferences]
public sealed partial class InvestigationExaminableWindow : FancyWindow
{

    public InvestigationExaminableWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(InvestigationExaminableEuiState state, IEntityManager entManager)
    {
        InvestigateContent.SetMessage(state.InvestigateContent);
    }


}
